### ISSUE TITLE
QoS 1 dropped messages on benchmark

### ISSUE THREAD

**Issue by fracasula** [emqx/emqx#4439]
Hello, I'm evaluating the EMQX Broker for the company I work for but I'm having some issues with dropped messages in my benchmark.

I'm using EMQ X Broker 4.3-rc.1 via Docker, no clustering, just a single node started via `make` like this:

```
.PHONY: emq-start
emq-start:
	docker run --rm -it \
		--name emqx-broker \
		-e EMQX_LOG__TO=console \
		-e EMQX_LOG__LEVEL=debug \
		-e EMQX_BROKER__SHARED_SUBSCRIPTION_STRATEGY=hash \
		-e EMQX_ZONE__INTERNAL__MAX_MQUEUE_LEN=0 \
		-e EMQX_ZONE__INTERNAL__MAX_INFLIGHT=10000000 \
		-p 1883:11883 -p 18083:18083 \
		emqx/emqx
```

As you can see I'm just focusing on the `internal` zone here, I tried also with a smaller `max_inflight` which shouldn't affect the dropped messages anyway. Given that messages of disconnected clients are stored in the queue (also if max inflight is reached that should be the case according to the docs) and given that I set a `MAX_MQUEUE_LEN=0` I was expecting to see no dropped messages (`0` there means no limit, right?).

My client is configured like this:

```
.PHONY: test-emq-start
test-emq-start: build
	$(eval EMQX_IP:= $(shell docker inspect emqx-broker | grep 'IPAddress": "' | tail -n 1 | awk '{print $$2}' | sed 's/"//g' | sed 's/,//g'))
	docker run --rm -it \
		--entrypoint=bash \
		mqtt-tests:latest \
		-c "./mqtt-test --addr=$(EMQX_IP):1883 -recv-max=65535 -consumers=1 -producers=100 -messages=10000"
```

It's using the `1883` port but if you notice the port mapping when I start EMQX (see first snippet) that is actually `11883` (which should be the port for the `internal` zone/listener as far as I understand).

My test is explicitly trying to swamp a slow consumer with a lot of messages, so lots of fast publishers and one consumer only.
I have 100 producers publishing 10k messages each which accounts to a million messages that the consumer should slowly consume without any drops in between.

The client `ReceiveMaximum` is the MQTT v5 default (i.e. `65535`) and the `SessionExpiryInterval` that the client specifies in the `CONNECT` packet is `0xffffffff` which means no session expiration.

Unfortunately with this setup I see a lot of dropped messages. Here's how I get the metrics while my test is running:

```
.PHONY: emq-metrics
emq-metrics:
	$(eval EMQX_HOSTNAME:= $(shell docker inspect emqx-broker | grep 'Hostname": "' | tail -n 1 | awk '{print $$2}' | sed 's/"//g' | sed 's/,//g'))
	$(eval EMQX_IP:= $(shell docker inspect emqx-broker | grep 'IPAddress": "' | tail -n 1 | awk '{print $$2}' | sed 's/"//g' | sed 's/,//g'))
	docker exec -it -e EMQX_NODE_NAME="$(EMQX_HOSTNAME)@$(EMQX_IP)" emqx-broker emqx_ctl broker metrics | grep -i "drop\|error\|missed"
```

Which shows the following:

```
actions.error                 : 0
delivery.dropped              : 0
delivery.dropped.expired      : 0
delivery.dropped.no_local     : 0
delivery.dropped.qos0_msg     : 0
delivery.dropped.queue_full   : 0
delivery.dropped.too_large    : 0
messages.dropped              : 779290
messages.dropped.expired      : 0
messages.dropped.no_subscriber: 779290
packets.connack.auth_error    : 0
packets.connack.error         : 0
packets.puback.missed         : 0
packets.pubcomp.missed        : 0
packets.publish.auth_error    : 0
packets.publish.dropped       : 0
packets.publish.error         : 0
packets.pubrec.missed         : 0
packets.pubrel.missed         : 0
packets.subscribe.auth_error  : 0
packets.subscribe.error       : 0
packets.unsubscribe.error     : 0
```

That is a huge 77.93% of messages dropped. I have either misunderstood the `max_mqueue_len` setting and how zone/listeners work or perhaps the settings that I'm passing via Docker environment variables are not being applied. How can I check if they are being applied considering that are not being written in the config file?

Any suggestions/tips on how to achieve this would be really appreciated. Thanks.

**EDIT:**
1. there is no authentication involved given that `internal` by default allows for anonymous access

**Comment by tigercl** [comment]
@fracasula Sorry for not responding to you in time, and thank you for such detailed feedback. Regarding the dropped messages, I see `messages.dropped.no_subscriber` metric. It seems that the messages are all dropped because there are no subscribers? I saw you mentioned that the `Session Expiry Interval` specified by the client is 0xFFFFFFFF, but what is the value of `Clean Start`? The value of `Clean Start` determines whether the client will use a new session when connecting.

**Comment by fracasula** [comment]
@tigercl thanks for getting back to me! Yes, of course I'm using `CleanStart: false`, this is how I'm building the `CONNECT` packet via the [Eclipse Paho library](https://github.com/eclipse/paho.golang):

```go
var receiveMaximum uint16 = 65535
var sessionExpiryInterval uint32 = 0xffffffff
cp := paho.Connect{
	ClientID:   clientID,
	KeepAlive:  30,
	CleanStart: false,
	Properties: &paho.ConnectProperties{
		ReceiveMaximum:        &receiveMaximum,
		SessionExpiryInterval: &sessionExpiryInterval,
	},
}
```

I'm not passing anything else but let me give you a bit more background. At [Netdata](https://github.com/netdata/netdata) we're using VerneMQ in production but it doesn't give us in-order delivery with shared subscriptions (we could do it with EMQX thanks to the `hash_clientid` setting) and their clustering is broken (we're having issues during split brains, e.g. message loss). I therefore decided to build a test to compare it with your broker instead. The client code is exactly the same and I can run it against VMQ or against EMQX. When I run it against VMQ with `max_online_messages=-1` and `max_offline_messages=-1` I have no dropped messages. The client and its settings are exactly the same, I run it against EMQX and I get those dropped messages mentioned in my first post. Is there some setting that I'm missing?

**Notes:**
* the consumer client gets disconnected with an error and I'm not handling reconnections in my test for now so it stays disconnected while publishers keep on pushing
* even though the consumer gets disconnected at some point, given `EMQX_ZONE__INTERNAL__MAX_MQUEUE_LEN` I should not see dropped messages anyway, right?
* the consumer gets disconnected only if the 100 publishers push 10k messages each, it does not happen with 1k each
* please find attached the output of the EMQX broker console

[logs.txt](https://github.com/emqx/emqx/files/6220443/logs.txt)

**Comment by tigercl** [comment]
@fracasula I think EMQ X Broker lost the subscription or cleared the session during the client disconnection. Of course, based on previous experience, I prefer to clear the session.
Perhaps some errors in EMQ X Broker caused the client to disconnect, but I still cannot determine the specific error. I suggest you set the log level to warning, because the debug level will greatly affect performance during benchmark and may flush error logs.

**Comment by fracasula** [comment]
@tigercl I can re-run it with a warning log level, sure, but that's not the point. I opened the issue because I'd like to understand if it's possible to avoid dropped messages in the first place. Client errors happen, they can happen for a variety of reasons. The point is that I do not want to lose messages if they happen. So if we set `EMQX_ZONE__INTERNAL__MAX_MQUEUE_LEN` to `0` and the client is connecting with `CleanStart: false` and `SessionExpiryInterval: 0xffffffff` then we should not see any dropped messages regardless of client disconnections, correct?

**Comment by fracasula** [comment]
@tigercl 

```
2021-03-30 07:42:56.623 [warning] [Alarm Handler] Alarm mqtt_conn/congested/consumer-0/undefined/too_many_publish is activated, MQTT connection congested: consumer-0/undefined/too_many_publish
2021-03-30 07:42:59.316 [error]      Process:          <0.2057.0> on node '5ccba3d86f2a@172.17.0.2'
     Context:          maximum heap size reached
     Max Heap Size:    8388608
     Total Heap Size:  9078381
     Kill:             false
     Error Logger:     true
     GC Info:          [{old_heap_block_size,3581853},
                        {heap_block_size,5472277},
                        {mbuf_size,60964},
                        {recent_size,1268900},
                        {stack_size,24},
                        {old_heap_size,0},
                        {heap_size,2450686},
                        {bin_vheap_size,2471},
                        {bin_vheap_block_size,46422},
                        {bin_old_vheap_size,0},
                        {bin_old_vheap_block_size,46422}]
```

Is that the reason why it's disconnecting the client and dropping the messages? Can we change some configuration on the broker to avoid the dropping somehow?

**Comment by zmstone** [comment]
Hi @fracasula 
slightly related, we have merged a fix 6c77fa1b which is to be released in rc.2.
`EMQX_ZONE__INTERNAL__MAX_INFLIGHT=10000000` this config will not be valid,
maximum allowed will be 65535, otherwise there is a risk of overflow.

**Comment by fracasula** [comment]
> Hi @fracasula
> slightly related, we have merged a fix [6c77fa1](https://github.com/emqx/emqx/commit/6c77fa1bf7fe46683d4a5169fb184c602a1dc0fe) which is to be released in rc.2.
> `EMQX_ZONE__INTERNAL__MAX_INFLIGHT=10000000` this config will not be valid,
> maximum allowed will be 65535, otherwise there is a risk of overflow.

@zmstone Amazing, if I set `EMQX_ZONE__INTERNAL__MAX_INFLIGHT` to `65535` the consumer gets through all the messages and I see no drops.

Unfortunately if I make the consumer wait 10 seconds before sending a `PUBACK` back I get the same issue.

```
2021-03-30 08:30:10.109 [warning] [Alarm Handler] Alarm mqtt_conn/congested/consumer-0/undefined/too_many_publish is activated, MQTT connection congested: consumer-0/undefined/too_many_publish
2021-03-30 08:30:10.907 [error]      Process:          <0.2055.0> on node '23ae2976dfdc@172.17.0.2'
     Context:          maximum heap size reached
     Max Heap Size:    8388608
     Total Heap Size:  9207420
     Kill:             false
     Error Logger:     true
     GC Info:          [{old_heap_block_size,3581853},
                        {heap_block_size,5472277},
                        {mbuf_size,153402},
                        {recent_size,1273921},
                        {stack_size,110},
                        {old_heap_size,0},
                        {heap_size,2487284},
                        {bin_vheap_size,0},
                        {bin_vheap_block_size,46422},
                        {bin_old_vheap_size,0},
                        {bin_old_vheap_block_size,46422}]
```

Once I get that warning I see lots of dropped messages:

```
actions.error                 : 0
delivery.dropped              : 0
delivery.dropped.expired      : 0
delivery.dropped.no_local     : 0
delivery.dropped.qos0_msg     : 0
delivery.dropped.queue_full   : 0
delivery.dropped.too_large    : 0
messages.dropped              : 45521
messages.dropped.expired      : 0
messages.dropped.no_subscriber: 45521
packets.connack.auth_error    : 0
packets.connack.error         : 0
packets.puback.missed         : 0
packets.pubcomp.missed        : 0
packets.publish.auth_error    : 0
packets.publish.dropped       : 0
packets.publish.error         : 0
packets.pubrec.missed         : 0
packets.pubrel.missed         : 0
packets.subscribe.auth_error  : 0
packets.subscribe.error       : 0
packets.unsubscribe.error     : 0
```

**Comment by zmstone** [comment]
just did a test, `-e EMQX_ZONE__INTERNAL__MAX_MQUEUE_LEN=0` this config should take effect,
You may check `data/app.<time>.config` to confirm, it should contain:

```
     {internal,
      [{max_mqueue_len,0},
```

**Comment by zmstone** [comment]
> @zmstone Amazing, if I set EMQX_ZONE__INTERNAL__MAX_INFLIGHT to 65535 the consumer gets through all the messages and I see no drops.

Thanks for testing it out. This is new to me, I thought overflow may only cause the connection to crash.
still not quite familiar with the code base ;-)

**Comment by fracasula** [comment]
> Unfortunately if I make the consumer wait 10 seconds before sending a `PUBACK` back I get the same issue.

Even now and then it still happens even without the `PUBACK` artificial delay :thinking: I'll check the `data/` folder to see if the settings are being applied :bow:

**Comment by zmstone** [comment]
> > Unfortunately if I make the consumer wait 10 seconds before sending a `PUBACK` back I get the same issue.
> 
> Even now and then it still happens even without the `PUBACK` artificial delay 🤔 I'll check the `data/` folder to see if the settings are being applied 🙇

I am looking into this.

**Comment by fracasula** [comment]
@zmstone 

```
     {internal,                                                 
      [{use_username_as_clientid,false},                        
       {upgrade_qos,false},                                     
       {strict_mode,false},                                     
       {session_expiry_interval,7200},                          
       {retry_interval,30},                                     
       {mqueue_store_qos0,true},                             
       {mqueue_priorities,none},        
       {mqueue_default_priority,lowest},
       {max_subscriptions,0},                  
       {max_mqueue_len,0},              
       {max_inflight,65535},                   
       {max_awaiting_rel,1000},         
       {keepalive_backoff,0.75},        
       {ignore_loop_deliver,false},     
       {idle_timeout,15000},            
       {force_shutdown_policy,          
        #{max_heap_size => 8388608,message_queue_len => 10000}},
       {enable_stats,true},                                     
       {enable_flapping_detect,false},                          
       {enable_ban,false},                                      
       {enable_acl,false},                                      
       {bypass_auth_plugins,true},                              
       {await_rel_timeout,300},                                 
       {allow_anonymous,true},                                  
       {acl_deny_action,ignore}]}]},
```

:point_up: looks good to me :thinking: 

@zmstone is there some dashboard/cli-tool I can use to make sure that I'm connecting to the `internal` zone? I mean, the port forward looks correct but just in case I'd like to double check.

**Comment by zmstone** [comment]
> @zmstone is there some dashboard/cli-tool I can use to make sure that I'm connecting to the internal zone? I mean, the port forward looks correct but just in case I'd like to double check.

you can use command `bin/emqx_ctl listeners` to view some details.

**Comment by fracasula** [comment]
> you can use command `bin/emqx_ctl listeners` to view some details.

@zmstone thank you, that's very useful! I can confirm that I'm connecting to the right zone but I had to add this my `docker run`: `-e EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883`.

```
mqtt:tcp:internal
  listen_on       : 0.0.0.0:11883
  acceptors       : 4
  max_conns       : 1024000
  current_conn    : 100
  shutdown_count  : [{takeovered,2},{proc_heap_too_large,1}]
```

Now I believe that it's connecting to the right zone. I can still see the heap error messages but no dropped messages! :tada: 

I'll re-run the tests later with a late `PUBACK` to test the behaviour there. Thanks again for the help so far :bow:

**Comment by zmstone** [comment]
Please note that EMQ X open source edition so far do not support session message persistence.
As you can see there were 3 shutdowns, maybe that's causing the message loss.
The congestion alarm does not cause shutdown, but this does:
```
       {force_shutdown_policy,          
        #{max_heap_size => 8388608,message_queue_len => 10000}},
```
If you want to allow RAM usage for one connection to grow indefinitely, you can use `0` to disable them.

P.S. one minor update:

> we have merged a fix 6c77fa1 which is to be released in rc.2.

The next RC is `4.3-rc.3` which will be released soon.

**Comment by zmstone** [comment]
Thank you @fracasula for closing the issue.
Follow up actions are always appreciated.
