### ISSUE TITLE
Emqx in docker rare crash

### ISSUE THREAD

**Issue by velimirj** [emqx/emqx#4630]
**Environment**:

- EMQ X version (e.g. `emqx_ctl status`): 4.2.10
- Hardware configuration (e.g. `lscpu`): /
- OS (e.g. `cat /etc/os-release`): /
- Kernel (e.g. `uname -a`): /
- Erlang/OTP version (in case you build emqx from source code): /
- Others: /

**What happened and what you expected to happen**: 
Every once in a while, when doing `docker-compose up -d` with the docker-compose file which includes two services using emqx image, one or both of them crash and keep crashing when automatically restarted because of docker-compose. This keeps happening until `docker-compose down` and `docker-compose up -d` is done.

emqx.log contents:
```2021-04-16 14:04:09.321 [error] ** State machine gen_rpc_server_tcp terminating
** When server state  = {undefined,undefined}
** Reason for termination = exit:badarg
** Callback modules = [gen_rpc_server]
** Callback mode = undefined
** Stacktrace =
**  [{inet_tcp,listen,2,[{file,"inet_tcp.erl"},{line,160}]},
     {gen_rpc_server,init,1,[{file,"gen_rpc_server.erl"},{line,56}]},
     {gen_statem,init_it,6,[{file,"gen_statem.erl"},{line,718}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]

2021-04-16 14:04:09.322 [error]     supervisor: {local,gen_rpc_sup}
    errorContext: start_error
    reason: badarg
    offender: [{pid,undefined},
               {id,gen_rpc_server_tcp},
               {mfargs,{gen_rpc_server,start_link,[tcp]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
2021-04-16 14:04:09.322 [error]   crasher:
    initial call: application_master:init/4
    pid: <0.1379.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,gen_rpc_server_tcp,badarg}},
                     {gen_rpc_app,start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.1378.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.1380.0>,normal}]
    links: [<0.1378.0>,<0.1288.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:
  ```

**How to reproduce it (as minimally and precisely as possible)**:
Here is Dockerfile and config files used to build custom emqx image: [emqx.zip](https://github.com/emqx/emqx/files/6334286/emqx.zip)

```
version: '3.5'
services:
    emqx1:
        image: emqx-test:latest
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
    emqx2:
        image: emqx-test:latest
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
          - EMQX_LISTENER__TCP__EXTERNAL=2883
          - EMQX_LISTENER__SSL__EXTERNAL=7883
          - EMQX_LISTENER__WS__EXTERNAL=7083
          - EMQX_LISTENER__WSS__EXTERNAL=7084
          - EMQX_ALLOW_ANONYMOUS=false
 ```

**Anything else we need to know?**:
/

**Comment by airclear** [comment]
同问

**Comment by Rory-Z** [comment]
Hi, @velimirj 
I noticed that the image you are using is `emqx-test:latest`. This is not the image we released. Can you tell us what this image does?

**Comment by velimirj** [comment]
Hi @Rory-Z, 
I attached emqx.zip file in the original post, in there you can find Dockerfile and configuration files that I am using. 
Thank you for helping!

**Comment by Rory-Z** [comment]
Hi, @velimirj Can you use `FROM emqx/emqx:4.2.10` in Dockerfile, and retry

**Comment by velimirj** [comment]
Hi @Rory-Z, I've used your official image directly in docker-compose, and I'm still getting the same error after doing docker-compose down and up a number of times.
```
version: '3.5'
services:
    emqx1:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
    emqx2:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
        environment:
          - EMQX_LOADED_PLUGINS="emqx_retainer, emqx_management, emqx_dashboard, emqx_web_hook, emqx_auth_http"
          - EMQX_LISTENER__TCP__EXTERNAL=2883
          - EMQX_LISTENER__SSL__EXTERNAL=7883
          - EMQX_LISTENER__WS__EXTERNAL=7083
          - EMQX_LISTENER__WSS__EXTERNAL=7084
          - EMQX_ALLOW_ANONYMOUS=false
   ```

**Comment by velimirj** [comment]
I've added even more emqx services, and now almost always at least one container fails to start because of a crash.
```version: '3.5'
services:
    emqx1:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
    emqx2:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
    emqx3:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
    emqx4:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
    emqx5:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
    emqx6:
        image: emqx/emqx:4.2.10
        restart: unless-stopped
```

**Comment by k32** [comment]
I cannot reproduce the problem with the above docker-compose file on Ubuntu groovy. Which OS, version of docker and docker-compose are you using?

**Comment by velimirj** [comment]
Hi @k32, locally I'm using wsl2:

```NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
Docker version 19.03.8, build afacb8b7f0
```

```
docker-compose version 1.25.3, build d4d1b42b
```

and on the cloud:
```NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```
Docker version 19.03.6, build 369ce74a3c
```

```
docker-compose version 1.17.1, build unknown
```

I'm having the same issue in both cases.

**Comment by k32** [comment]
Just to clarify:
1) You don't use WSL in the cloud?
2) Docker-compose file from this message: https://github.com/emqx/emqx/issues/4630#issuecomment-823281631 is the full file, without any additional configurations skipped?

The error looks like network configuration for the `gen_rpc` listener is incorrect (either IP or port has wrong type)

**Comment by velimirj** [comment]
1. That's right.
2. It is the full file.

Is there anything I can do to debug this? It seems to me like some kind of race condition type of issue.

**Comment by k32** [comment]
Thanks for the answers. I actually managed to reproduce the problem by increasing the number of containers to 13. This will simplify things.

**Comment by k32** [comment]
Found the root cause. From `gen_rpc_helper.erl` (one of our dependencies):

```
%% @doc Figure out dist port from node's name.
-spec(port(node() | string()) -> inet:port_number()).
port(Name) when is_atom(Name) ->
    port(atom_to_list(Name));
port(Name) when is_list(Name) ->
    %% Figure out the base port.
    BasePort = ?DEFAULT_LISTEN_PORT,
    %% Now, figure out our "offset" on top of the base port.  The
    %% offset is the integer just to the left of the @ sign in our node
    %% name.  If there is no such number, the offset is 0.
    %%
    %% Also handle the case when no hostname was specified.
    BasePort + offset(Name).

%% @doc Figure out the offset by node's name
offset(NodeName) ->
    ShortName = re:replace(NodeName, "@.*$", ""),
    case re:run(ShortName, "[0-9]+$", [{capture, first, list}]) of
        nomatch -> 0;
        {match, [OffsetAsString]} ->
            list_to_integer(OffsetAsString)
    end.
```

Basically, it tries to guess port based on the node name. This code expects that the node name is something like `emqx1`, `emqx2`, etc... 
When you start containers without specifying  `EMQX_NODE_NAME` environment variable, EMQ X uses docker container id as the node name. This id is random, and sometimes it can create a large port offset.
Workaround: specify `EMQX_NODE_NAME` environment variable as shown here: https://docs.emqx.io/en/broker/v4.3/getting-started/install.html#create-a-simple-static-cluster-by-docker-compose

In the meanwhile we will discuss what to do with this code, I don't think it should be enable by default.

**Comment by velimirj** [comment]
Thank you a lot!

**Comment by k32** [comment]
Thanks for the bug report, closing in favor of https://github.com/emqx/emqx/issues/4647 , which has clearer description.
