### ISSUE TITLE
emqx container not using emqx.conf file

### ISSUE THREAD

**Issue by openedhardware** [emqx/emqx#7093]
### Subject of the issue
emqx container not using emqx.conf file

### Your environment

Log archive: [node_dump_20220221_222632.tar.gz](https://github.com/emqx/emqx/files/8112375/node_dump_20220221_222632.tar.gz)

- EMQ X version (e.g. `emqx_ctl status`): 
  ```Node '6e1218b55bbf@172.17.0.2' 4.3.11 is started```
- OS (e.g. `cat /etc/os-release`):
  ```bash-5.0# cat /etc/os-release
  NAME="Alpine Linux"
  ID=alpine
  VERSION_ID=3.12.9
  PRETTY_NAME="Alpine Linux v3.12"
  HOME_URL="https://alpinelinux.org/"
  BUG_REPORT_URL="https://bugs.alpinelinux.org/"
  ```
- Kernel (e.g. `uname -a`):
  ```
  bash-5.0# uname -a
  Linux 6e1218b55bbf 5.2.10-yocto-standard #1 SMP PREEMPT Fri Aug 30 04:33:44 UTC 2019 x86_64 Linux
  ```

### Steps to reproduce
I am using the following `Dockerfile` to run the emqx 4.3.11 container:
```docker
FROM emqx/emqx:4.3.11-alpine-amd64

ENV EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_username,emqx_recon,emqx_retainer,emqx_dashboard,emqx_bridge_mqtt"

COPY emqx_bridge_mqtt.conf /opt/emqx/etc/plugins/emqx_bridge_mqtt.conf
COPY emqx_retainer.conf /opt/emqx/etc/plugins/emqx_retainer.conf

USER root
COPY emqx.conf /opt/emqx/etc/emqx.conf
CMD ["/opt/emqx/bin/emqx",  "foreground"]
```

### Expected behaviour
In my `emqx.conf` file, I set `log.to` as `both`, so the logs should be outputted to the console and also to a file.

### Actual behaviour
I have checked the log of my container and it says:
```
EMQX_LOADED_PLUGINS=emqx_management emqx_auth_username emqx_recon emqx_retainer emqx_dashboard emqx_bridge_mqtt
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
log.to = "console"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "6e1218b55bbf@172.17.0.2"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
Starting emqx on node 6e1218b55bbf@172.17.0.2
Start mqtt:tcp:internal listener on 127.0.0.1:11883 successfully.
Start mqtt:tcp:external listener on 0.0.0.0:1883 successfully.
Start mqtt:ws:external listener on 0.0.0.0:8083 successfully.
Start mqtt:ssl:external listener on 0.0.0.0:8883 successfully.
Start mqtt:wss:external listener on 0.0.0.0:8084 successfully.
2022-02-21T22:04:54.672600+00:00 [alert] [Plugins] cannot_find_plugins: [emqx_auth_username]
Start http:management listener on 8081 successfully.
Start http:dashboard listener on 18083 successfully.
EMQ X Broker 4.3.11 is running now!
```
No idea why it says `log.to = "console"`!

Inside the container, I can see the copied `emqx.conf` file:
```
bash-5.0# ls /opt/emqx/etc/emqx.conf 
/opt/emqx/etc/emqx.conf
```

Please help!

**Comment by zmstone** [comment]
Hi
There is an implicit override in docker entrypoint script.
Please set `ENQX_LOG__TO=both` for docker run

**Comment by openedhardware** [comment]
Hi, @zmstone 

`log.to` is just an example. I do have a number of customized configurations in my emqx.conf file...

**Comment by zmstone** [comment]
> Hi, @zmstone
> 
> `log.to` is just an example. I do have a number of customized configurations in my emqx.conf file...

Could you please provide another example?

**Comment by openedhardware** [comment]
I may have to compare my `emqx.conf` file with the original one.
But this is a but that should be fixed, isn't it?

**Comment by zmstone** [comment]
Btw. The config printed at boot are all overrides from the entrypoint script.
A workaround is to use your own entrypoint since  you are “repacking” it anyway

**Comment by zmstone** [comment]
> I may have to compare my `emqx.conf` file with the original one.
> 
> The emqx container doesn't use the `/opt/emqx/etc/emqx.conf` file literally... This is a bug that should be fixed, isn't it?

Sure if the file is there and it’s not being used, then it’s a bug

**Comment by openedhardware** [comment]
I have checked the entrypoint of the original image(`/usr/bin/docker-entrypoint.sh`) but couldn't find any issue...

**Comment by openedhardware** [comment]
It's really easy to replicate on your end...

Here is my testing Dockerfile:
```
FROM emqx/emqx:4.3.12
COPY emqx.conf /opt/emqx/etc/emqx.conf
CMD ["/opt/emqx/bin/emqx",  "foreground"]
```

And prepare the `emqx.conf` file and change its `log.to` to `both`.

Could you try on your end and find the reason?

**Comment by zmstone** [comment]
i think i found it,
the issue is here:
`https://github.com/emqx/emqx/blob/3be4f30f8cf32fd9c08a2b8592e0130e6d7da371/deploy/docker/Dockerfile#L63`
etc is a docker volume. (this has been fixed in 5.0, but not for 4.x)

**Comment by zmstone** [comment]
```
FROM emqx/emqx:4.3.12
RUN cp -R /opt/emqx/etc/ /opt/emqx/etc2
RUN echo "RUNNER_ETC_DIR=/opt/emqx/etc2" >> /opt/emqx/releases/emqx_vars
COPY emqx.conf /opt/emqx/etc2/emqx.conf
CMD ["/opt/emqx/bin/emqx",  "foreground"]
```

**Comment by openedhardware** [comment]
> ```
> FROM emqx/emqx:4.3.12
> RUN cp -R /opt/emqx/etc/ /opt/emqx/etc2
> RUN echo "RUNNER_ETC_DIR=/opt/emqx/etc2" >> /opt/emqx/releases/emqx_vars
> COPY emqx.conf /opt/emqx/etc2/emqx.conf
> CMD ["/opt/emqx/bin/emqx",  "foreground"]
> ```

I assume this isn't needed from version 5?

**Comment by zmstone** [comment]
no, but version 5 is not released yet (rc soon).
unfortunately we can't change etc to a non-volume for 4.x for compatibility reasons.

**Comment by openedhardware** [comment]
@zmstone 

Sad, still seeing `log.to = "console"`!

`/opt/emqx/releases/emqx_vars` file content:

```
bash-5.0# cat /opt/emqx/releases/emqx_vars
######################################################################
## NOTE: Do NOT replace this file during release upgrade.
##       Update the vars to the end of this file instead.
######################################################################
## constants from relx template
REL_VSN="4.3.12"
ERTS_VSN="11.1.8"
ERL_OPTS=""
RUNNER_ROOT_DIR="$(cd $(dirname $(readlink $0 || echo $0))/..; pwd -P)"
RUNNER_BIN_DIR="$RUNNER_ROOT_DIR/bin"
RUNNER_LOG_DIR="$RUNNER_ROOT_DIR/log"
RUNNER_LIB_DIR="$RUNNER_ROOT_DIR/lib"
RUNNER_ETC_DIR="$RUNNER_ROOT_DIR/etc"
RUNNER_DATA_DIR="$RUNNER_ROOT_DIR/data"
RUNNER_USER=""

EMQX_LICENSE_CONF=''
export EMQX_DESCRIPTION='EMQ X Broker'

## computed vars
REL_NAME="emqx"
ERTS_PATH="$RUNNER_ROOT_DIR/erts-$ERTS_VSN/bin"

## updated vars here
RUNNER_ETC_DIR=/opt/emqx/etc2
```

And my emqx conf file:
```
bash-5.0# cat /opt/emqx/etc2/emqx.conf | grep log.to
log.to = both
```

Any idea why it doesn't use /opt/emqx/etc2/emqx.conf` file?

**Comment by zmstone** [comment]
add this to your `Dockerfile`.
`ENV EMQ_LOG__TO=both`

If not set, docker entrypoint overrides it to "console" and it does not respect what's set in emqx.conf

**Comment by openedhardware** [comment]
Hmm, how about other settings? Give up using `emqx.conf` file and then use the ENV for each configuration?

**Comment by zmstone** [comment]
sorry, for logging, it's not docker entrypoint, but the emqx boot command,
when starting emqx in `forground` or `console` mode, it forces logging to console unless `EMQX_LOG__TO` is set.
https://github.com/emqx/emqx/blob/3be4f30f8cf32fd9c08a2b8592e0130e6d7da371/bin/emqx#L652

all the other ones, namely are overridden from docker entrypoint.
```
listener.ssl.external.acceptors = "32"
listener.ssl.external.max_connections = "102400"
listener.tcp.external.acceptors = "64"
listener.tcp.external.max_connections = "1024000"
listener.ws.external.acceptors = "16"
listener.ws.external.max_connections = "102400"
listener.wss.external.acceptors = "16"
listener.wss.external.max_connections = "102400"
node.max_ets_tables = "2097152"
node.max_ports = "1048576"
node.name = "6e1218b55bbf@172.17.0.2"
node.process_limit = "2097152"
rpc.port_discovery = "manual"
```
https://github.com/emqx/emqx/blob/3be4f30f8cf32fd9c08a2b8592e0130e6d7da371/deploy/docker/docker-entrypoint.sh#L30-L91

**Comment by zmstone** [comment]
> Hmm, how about other settings? Give up using `emqx.conf` file and then use the ENV for each configuration?

all the overridden logs are printed to the console when EMQX boots up.
these ones, you'll have to override using env variables.

**Comment by openedhardware** [comment]
This is really weird.. 

Added `ENV EMQ_LOG__TO=both` to my Dockerfile, but still seeing `log.to = "console"`!

**Comment by zmstone** [comment]
sorry, my bad, it's `EMQX_LOG__TO`

**Comment by openedhardware** [comment]
Ok, it works and other configurations in my `emqx.conf` as well!

Thanks for your help!

**Comment by zmstone** [comment]
you're welcome.
I've sent a PR to fix the volume issue
https://github.com/emqx/emqx/pull/7102

**Comment by ULTRAKID** [comment]
> sorry, for logging, it's not docker entrypoint, but the emqx boot command, when starting emqx in `forground` or `console` mode, it forces logging to console unless `EMQX_LOG__TO` is set.
> 
> https://github.com/emqx/emqx/blob/3be4f30f8cf32fd9c08a2b8592e0130e6d7da371/bin/emqx#L652
> 
> all the other ones, namely
> 
> ```
> listener.ssl.external.acceptors = "32"
> listener.ssl.external.max_connections = "102400"
> listener.tcp.external.acceptors = "64"
> listener.tcp.external.max_connections = "1024000"
> listener.ws.external.acceptors = "16"
> listener.ws.external.max_connections = "102400"
> listener.wss.external.acceptors = "16"
> listener.wss.external.max_connections = "102400"
> node.max_ets_tables = "2097152"
> node.max_ports = "1048576"
> node.name = "6e1218b55bbf@172.17.0.2"
> node.process_limit = "2097152"
> rpc.port_discovery = "manual"
> ```
> 
> are overridden from docker entrypoint.
> 
> https://github.com/emqx/emqx/blob/3be4f30f8cf32fd9c08a2b8592e0130e6d7da371/deploy/docker/docker-entrypoint.sh#L30-L91

Hey, I wanna know why export so many env in docker entrypoint? I can understand the reason for EMQX_LOG__TO in docker, but is the other config necessary for env in docker? Is there any problem I change all the other ones in docker entrypoint, then rebuild the image? Thanks a lot. @zmstone zmstone

**Comment by zmstone** [comment]
I believe below are unnecessarily duplicated with defaults from emqx.conf
``
EMQX_NODE__PROCESS_LIMIT
EMQX_NODE__MAX_PORTS
EMQX_LISTENER__*
```

And `EMQMX_K8S__*` are only applicable when running in k8s and want to use k8s APIs for cluster auto-discovery, so feel free to delete when not running in k8s.

What's most important to set when running in docker: `$EMQX_NODE_NAME` (or `$EMQX_NAME@$EMQX_HOST`).

It's not a hard requirement to set `EMQX_LOG__TO`, if not set by entrypoint, it'll be set to `console` in `bin/emqx` when running in `foreground` mode (which is the default mode for docker).

**Comment by ULTRAKID** [comment]
> 

Got it.  (o゜▽゜)o☆
